service: cognito-example

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    AUTHSIGNAL_SECRET: hg372duzX8fDDdP5a5ArlHTZW49DiBJ3TzbmHvP+1xg/mMKrwhUNGQ==
    AUTHSIGNAL_URL: https://dev-api.authsignal.com/v1

package:
  individually: true

functions:
  defineAuthChallenge:
    handler: lambdas/define-auth-challenge.handler

  createAuthChallenge:
    handler: lambdas/create-auth-challenge.handler

  verifyAuthChallengeResponse:
    handler: lambdas/verify-auth-challenge-response.handler

  preSignUp:
    handler: lambdas/pre-sign-up.handler
