service: cognito-example

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    AUTHSIGNAL_SECRET: YOUR_SECRET_KEY
    AUTHSIGNAL_URL: YOUR_REGION_URL

package:
  individually: true

functions:
  defineAuthChallenge:
    handler: lambdas/define-auth-challenge.handler

  createAuthChallenge:
    handler: lambdas/create-auth-challenge.handler

  verifyAuthChallengeResponse:
    handler: lambdas/verify-auth-challenge-response.handler

  preSignUp:
    handler: lambdas/pre-sign-up.handler
